-- AUTO-GENERATED. Do not edit by hand.
-- coding: utf-8 'ä
-- Source: LotroCompanion/lotro-data official EN/FR localization tables.
-- English and French values are joined by identical localization IDs.

TR_OfficialLocRaw = TR_OfficialLocRaw or {}
TR_OfficialZoneRaw = TR_OfficialZoneRaw or {}
TR_OfficialAreaRaw = TR_OfficialAreaRaw or {}

TR_OfficialLocRaw["Abodes of Erebor"] = "Habitations d'Erebor - Voyage rapide" -- travelsWeb.xml: Abodes of Erebor - Swift Travel
TR_OfficialLocRaw["Adambel"] = "Adambel" -- travelsMap.xml: Adambel
TR_OfficialLocRaw["Adso's Camp"] = "Camp d'Adso" -- travelsMap.xml: Adso's Camp
TR_OfficialLocRaw["Aethir"] = "Aerthir" -- travelsMap.xml: Aerthir
TR_OfficialLocRaw["Agarnaith Ranger Camp"] = "Camp des Rôdeurs d'Agarnaith" -- travelsMap.xml: Agarnaith Ranger Camp
TR_OfficialLocRaw["Ahaba"] = "Ahâba" -- travelsMap.xml: Ahâba
TR_OfficialLocRaw["Akraz-zahar"] = "Akrâz-zahar (Erebor) - Voyage rapide" -- travelsWeb.xml: Akrâz-zahar (Erebor) - Swift Travel
TR_OfficialLocRaw["Aldburg"] = "Aldburg" -- travelsMap.xml: Aldburg
TR_OfficialLocRaw["Amdan"] = "Amdân" -- travelsWeb.xml: Amdân
TR_OfficialLocRaw["Amon Raith"] = "Amon Raith" -- travelsMap.xml: Amon Raith
TR_OfficialLocRaw["Anazarmekhem"] = "Anazârmekhem" -- travelsMap.xml: Anazârmekhem
TR_OfficialLocRaw["Andrath"] = "Andrath" -- travelsMap.xml: Andrath
TR_OfficialLocRaw["Annak-khurfu"] = "Annâk-khurfu" -- travelsMap.xml: Annâk-khurfu
TR_OfficialLocRaw["Annuminas"] = "Annuminas" -- travelsMap.xml: Annúminas
TR_OfficialLocRaw["Aragorn's Pavilion"] = "Pavillon d'Aragorn" -- travelsMap.xml: Aragorn's Pavilion
TR_OfficialLocRaw["Arhaim"] = "Arhaim" -- travelsMap.xml: Arhaim
TR_OfficialLocRaw["Arnach"] = "Arnach" -- travelsMap.xml: Arnach
TR_OfficialLocRaw["Asbaj-khirfin"] = "Asbaj-khîrfin (Nord-Est de Matugarde)" -- travelsMap.xml: Asbaj-khîrfin (North Eastern Máttugard)
TR_OfficialLocRaw["Ashmargathal"] = "Ashmargathâl" -- travelsWeb.xml: Ashmargathâl
TR_OfficialLocRaw["Aslíf"] = "Aslif (Tordesoif)" -- travelsMap.xml: Aslíf (Deepscrave)
TR_OfficialLocRaw["Aughaire"] = "Aughaire" -- travelsMap.xml: Aughaire
TR_OfficialLocRaw["Avardin"] = "Avardin" -- travelsMap.xml: Avardin
TR_OfficialLocRaw["Bail Avarc"] = "Bail Avarc - Rapide" -- travelsMap.xml: Bail Avarc - Swift
TR_OfficialLocRaw["Bar Hurin"] = "Bâr Húrin" -- travelsMap.xml: Bâr Húrin
TR_OfficialLocRaw["Barachen's Camp"] = "Camp de Barachen" -- travelsMap.xml: Barachen's Camp
TR_OfficialLocRaw["Barad Faen"] = "Barad Faen" -- travelsMap.xml: Barad Faen
TR_OfficialLocRaw["Barad Rill"] = "Barad Rill (Gondor royal)" -- travelsMap.xml: Barad Rill (King's Gondor)
TR_OfficialLocRaw["Bargstad"] = "Bargstad (fosse de Mâcherocs)" -- travelsMap.xml: Bárgstad (Pit of Stonejaws)
TR_OfficialLocRaw["Barnavon"] = "Barnavon" -- travelsMap.xml: Barnavon
TR_OfficialLocRaw["Barthost"] = "Barthost" -- travelsMap.xml: Barthost
TR_OfficialLocRaw["Bazanmanar"] = "Bazanmanar (Nord de Fond-de-fosse)" -- travelsMap.xml: Bazanmanar (Northern Clovengap)
TR_OfficialLocRaw["Beaconwatch"] = "Veillefeu" -- travelsMap.xml: Beaconwatch
TR_OfficialLocRaw["Bel Inzul"] = "Bel Inzûl" -- travelsMap.xml: Bel Inzûl
TR_OfficialLocRaw["Beneath Dar Laja"] = "Sous Dâr Laja" -- travelsMap.xml: Beneath Dâr Laja
TR_OfficialLocRaw["Beorninghus"] = "Beorninghus" -- travelsMap.xml: Beorninghús
TR_OfficialLocRaw["Blomgard"] = "Blomgard" -- travelsMap.xml: Blómgard
TR_OfficialLocRaw["Bloody Eagle Tavern"] = "Taverne de l'Aigle sanglant" -- travelsWeb.xml: The Bloody Eagle Tavern
TR_OfficialLocRaw["Boat to Lothlorien"] = "Lothlórien" -- travelsMap.xml: Lothlórien
TR_OfficialLocRaw["Boat to Mirkwood"] = "Forêt Noire" -- travelsMap.xml: Mirkwood
TR_OfficialLocRaw["Bree"] = "Bree" -- geoAreas.xml: Bree
TR_OfficialLocRaw["Breeland Festival Grounds"] = "Pré aux festivités du Pays de Bree - Voyage rapide" -- travelsWeb.xml: Bree-land Festival Grounds - Swift Travel
TR_OfficialLocRaw["Breeland Homesteads"] = "Résidences du Pays de Bree" -- travelsWeb.xml: Bree-land Homesteads
TR_OfficialLocRaw["Brockbridge"] = "Torrepont" -- travelsMap.xml: Brockbridge
TR_OfficialLocRaw["Brockenborings"] = "Trous des Grisards" -- travelsMap.xml: Brockenborings
TR_OfficialLocRaw["Brown Lands"] = "Terres brunes" -- travelsMap.xml: Brown Lands
TR_OfficialLocRaw["Buckland"] = "Pays de Bouc" -- travelsMap.xml: Buckland
TR_OfficialLocRaw["Bullroarer's Way"] = "Voie du Taureau mugissant" -- travelsMap.xml: Bullroarer's Way
TR_OfficialLocRaw["Byre Tor"] = "Byre Tor" -- travelsMap.xml: Byre Tor
TR_OfficialLocRaw["Calembel"] = "Calembel" -- travelsMap.xml: Calembel
TR_OfficialLocRaw["Camp of the Host"] = "Camp de l'armée" -- travelsMap.xml: Camp of the Host
TR_OfficialLocRaw["Cape of Belfalas"] = "Le Cap du Belfalas" -- geoAreas.xml: The Cape of Belfalas
TR_OfficialLocRaw["Cape of Belfalas Housing"] = "Résidences du Cap du Belfalas - Voyage rapide" -- travelsWeb.xml: Cape of Belfalas Homesteads - Swift Travel
TR_OfficialLocRaw["Caranost"] = "Caranost" -- travelsMap.xml: Caranost
TR_OfficialLocRaw["Caras Galadhon"] = "Caras Galadhon" -- travelsMap.xml: Caras Galadhon
TR_OfficialLocRaw["Caras Gelebren"] = "Caras Gelebren" -- travelsMap.xml: Caras Gelebren
TR_OfficialLocRaw["Celondim"] = "Celondim" -- travelsMap.xml: Celondim
TR_OfficialLocRaw["Cerdic's Camp"] = "Camp de Cerdic" -- travelsMap.xml: Cerdic's Camp
TR_OfficialLocRaw["Cerin Amroth"] = "Cerin Amroth" -- travelsMap.xml: Cerin Amroth
TR_OfficialLocRaw["Chamber of the Crossroads"] = "Salle de la Croisée des Chemins" -- travelsMap.xml: Chamber of the Cross-roads
TR_OfficialLocRaw["Clegur"] = "Clegur" -- travelsMap.xml: Clegur
TR_OfficialLocRaw["Cliving"] = "Cliving" -- travelsMap.xml: Cliving
TR_OfficialLocRaw["Combe"] = "Combe" -- travelsMap.xml: Combe
TR_OfficialLocRaw["Court of Celeborn"] = "Cour de Celeborn" -- dungeons.xml: Court of Celeborn
TR_OfficialLocRaw["Crithost"] = "Crithost" -- travelsMap.xml: Crithost
TR_OfficialLocRaw["Dagoras' Camp"] = "Camp de Dagoras" -- landmarks.xml: Dagoras' Camp
TR_OfficialLocRaw["Dale"] = "Dale" -- travelsMap.xml: Dale
TR_OfficialLocRaw["Derndingle"] = "Derunant" -- landmarks.xml: Derndingle
TR_OfficialLocRaw["Dinadab"] = "Dinadab (Gondor royal)" -- travelsMap.xml: Dinadab (King's Gondor)
TR_OfficialLocRaw["Dol Amroth"] = "Dol Amroth" -- travelsMap.xml: Dol Amroth
TR_OfficialLocRaw["Dolven-view"] = "Belvédère Enfoui" -- travelsMap.xml: Dolven-view
TR_OfficialLocRaw["Dom Goru"] = "Dôm Goru" -- travelsMap.xml: Dôm Goru
TR_OfficialLocRaw["Drenghol"] = "Drenghól" -- travelsMap.xml: Drenghól
TR_OfficialLocRaw["Duillond"] = "Duillond" -- travelsMap.xml: Duillond
TR_OfficialLocRaw["Dunfast's Refugees"] = "Réfugiés de Dunfast" -- travelsMap.xml: Dunfast's Refugees
TR_OfficialLocRaw["Dur Nagu"] = "Dur Nâgu" -- travelsMap.xml: Dur Nâgu
TR_OfficialLocRaw["Durin's Threshold"] = "Seuil de Durin" -- travelsMap.xml: Durin's Threshold
TR_OfficialLocRaw["Dwaling"] = "Dwaling" -- travelsMap.xml: Dwaling
TR_OfficialLocRaw["Díngarth"] = "Dingarth" -- travelsMap.xml: Díngarth
TR_OfficialLocRaw["East Pelargir"] = "Pelargir est" -- travelsMap.xml: East Pelargir
TR_OfficialLocRaw["Eastern Crossroads"] = "Carrefour de l'Est" -- travelsWeb.xml: Eastern Crossroads
TR_OfficialLocRaw["Eastfold Hills Homesteads"] = "Résidences des collines de l'Estfolde" -- travelsWeb.xml: Eastfold Hills Homesteads
TR_OfficialLocRaw["Eaworth"] = "Eaworth" -- travelsMap.xml: Eaworth
TR_OfficialLocRaw["Echad Andestel"] = "Echad Andestel" -- travelsMap.xml: Echad Andestel
TR_OfficialLocRaw["Echad Candelleth"] = "Echad Candelleth" -- travelsMap.xml: Echad Candelleth
TR_OfficialLocRaw["Echad Daervunn"] = "Echad Daervunn" -- travelsMap.xml: Echad Daervunn
TR_OfficialLocRaw["Echad Dagoras"] = "Echad Dagoras" -- travelsMap.xml: Echad Dagoras
TR_OfficialLocRaw["Echad Dunnan"] = "Echad Dunann" -- travelsMap.xml: Echad Dúnann
TR_OfficialLocRaw["Echad Eregion"] = "Echad Eregion" -- travelsMap.xml: Echad Eregion
TR_OfficialLocRaw["Echad Mirobel"] = "Echad Mirobel" -- travelsMap.xml: Echad Mirobel
TR_OfficialLocRaw["Echad Naeglanc"] = "Echad Naeglanc" -- travelsMap.xml: Echad Naeglanc
TR_OfficialLocRaw["Echad Sirion"] = "Echad Sirion" -- travelsMap.xml: Echad Sirion
TR_OfficialLocRaw["Echad Taerdim"] = "Echad Taerdim" -- travelsMap.xml: Echad Taerdim
TR_OfficialLocRaw["Echad Uial"] = "Echad Uial" -- travelsMap.xml: Echad Uial
TR_OfficialLocRaw["Echad-in-Edhil"] = "Echad-in-Edhil" -- travelsMap.xml: Echad-in-Edhil
TR_OfficialLocRaw["Edoras"] = "Edoras" -- travelsMap.xml: Edoras
TR_OfficialLocRaw["Elthengels"] = "Elthengels" -- travelsMap.xml: Elthengels
TR_OfficialLocRaw["Entwade"] = "Gué d'Ent" -- travelsMap.xml: Entwade
TR_OfficialLocRaw["Erebor"] = "Erebor" -- travelsMap.xml: Erebor
TR_OfficialLocRaw["Erynos"] = "Erynos" -- travelsMap.xml: Erynos
TR_OfficialLocRaw["Esteldin"] = "Esteldin" -- travelsMap.xml: Esteldín
TR_OfficialLocRaw["Estolad Lan"] = "Estolad Lân" -- travelsMap.xml: Estolad Lân
TR_OfficialLocRaw["Estolad Mernael"] = "Estolad Mernael" -- travelsMap.xml: Estolad Mernael
TR_OfficialLocRaw["Ethring"] = "Ethring" -- travelsMap.xml: Ethring
TR_OfficialLocRaw["Ettenmoors"] = "Landes d'Etten" -- travelsWeb.xml: Ettenmoors
TR_OfficialLocRaw["Falathorn Homesteads"] = "Propriétés de Falathlorn" -- travelsWeb.xml: Falathlorn Homesteads
TR_OfficialLocRaw["Faldham"] = "Faldham" -- travelsMap.xml: Faldham
TR_OfficialLocRaw["Faramir's Lookout"] = "Poste d'observation de Faramir" -- travelsMap.xml: Faramir's Look-out
TR_OfficialLocRaw["Fearwater Notch"] = "Enclave des Eaux troubles" -- travelsWeb.xml: Fearwater Notch
TR_OfficialLocRaw["Felegoth"] = "Felegoth" -- travelsMap.xml: Felegoth
TR_OfficialLocRaw["Fellgat"] = "Fellgat (Nord des Tassau-terres)" -- travelsMap.xml: Fellgát (Northern Welkin-lofts)
TR_OfficialLocRaw["Fenmarch"] = "Fenmarche" -- travelsMap.xml: Fenmarch
TR_OfficialLocRaw["Field of Onslaught"] = "Champ du carnage" -- geoAreas.xml: Field of Onslaught
TR_OfficialLocRaw["First Hall"] = "Première salle" -- travelsMap.xml: First Hall
TR_OfficialLocRaw["Fleet-gate"] = "Porte de la Flotte" -- travelsWeb.xml: Fleet-gate
TR_OfficialLocRaw["Floodwend"] = "Coudeflots" -- travelsMap.xml: Floodwend
TR_OfficialLocRaw["Forlaw"] = "Forloi" -- travelsMap.xml: Forlaw
TR_OfficialLocRaw["Forthbrond"] = "Brondavant" -- travelsMap.xml: Forthbrond
TR_OfficialLocRaw["Foxden Road"] = "Route du terrier de renard" -- travelsMap.xml: Foxden Road
TR_OfficialLocRaw["Furukzahar"] = "Furukzahar" -- travelsMap.xml: Furukzahar
TR_OfficialLocRaw["Gabilshathur"] = "Gabilshathûr" -- travelsMap.xml: Gabilshathûr
TR_OfficialLocRaw["Gadim-un"] = "Gadim-ûn" -- travelsMap.xml: Gadim-ûn
TR_OfficialLocRaw["Gaerond"] = "Gaerond" -- travelsMap.xml: Gaerond
TR_OfficialLocRaw["Galtrev"] = "Galtrev" -- travelsMap.xml: Galtrev
TR_OfficialLocRaw["Gamwich"] = "Gamwich" -- travelsMap.xml: Gamwich
TR_OfficialLocRaw["Gapholt"] = "Gapholt" -- travelsMap.xml: Gapholt
TR_OfficialLocRaw["Garsfeld"] = "Garsfeld" -- travelsMap.xml: Garsfeld
TR_OfficialLocRaw["Gate of Sorrows"] = "Porte du chagrin" -- travelsWeb.xml: Gate of Sorrows
TR_OfficialLocRaw["Gath Forthnir"] = "Gath Forthnir" -- travelsMap.xml: Gath Forthnír
TR_OfficialLocRaw["Gha Nekha"] = "Gha Nêkha" -- travelsMap.xml: Gha Nêkha
TR_OfficialLocRaw["Ghalburu"] = "Ghalbûru" -- travelsMap.xml: Ghalbûru
TR_OfficialLocRaw["Glaniath"] = "Glaniath" -- travelsMap.xml: Glaniath
TR_OfficialLocRaw["Gloin's Camp"] = "Camp de Gloïn" -- travelsMap.xml: Glóin's Camp
TR_OfficialLocRaw["Glyn Helyg"] = "Glyn Helyg" -- travelsMap.xml: Glyn Helyg
TR_OfficialLocRaw["Gondamon"] = "Gondamon" -- travelsMap.xml: Gondamon
TR_OfficialLocRaw["Grimbold's Camp"] = "Camp de Grimbold" -- travelsMap.xml: Grimbold's Camp
TR_OfficialLocRaw["Grimslade"] = "Grimslade" -- travelsMap.xml: Grimslade
TR_OfficialLocRaw["Grumachath"] = "Grumachath (Câr Bronach central)" -- travelsMap.xml: Grúmachath (Central Câr Bronach)
TR_OfficialLocRaw["Gwingris"] = "Gwingris" -- travelsMap.xml: Gwingris
TR_OfficialLocRaw["Haerondir"] = "Haerondir" -- landmarks.xml: Haerondir
TR_OfficialLocRaw["Hagbuth"] = "Hagbuth (Sud de Fond-de-fosse)" -- travelsMap.xml: Hagbuth (Southern Clovengap)
TR_OfficialLocRaw["Halach"] = "Halach" -- travelsMap.xml: Halach
TR_OfficialLocRaw["Hall of Flowing Water"] = "Salle des Cascades" -- travelsMap.xml: Hall of Flowing Water
TR_OfficialLocRaw["Hall of the King"] = "Palais du roi" -- dungeons.xml: Hall of the King
TR_OfficialLocRaw["Hall Under the Mtn"] = "Hall sous la montagne" -- dungeons.xml: Hall Under the Mountain
TR_OfficialLocRaw["Halrax"] = "Halrax" -- travelsMap.xml: Halrax
TR_OfficialLocRaw["Hammerstead"] = "Martelieu" -- travelsMap.xml: Hammerstead
TR_OfficialLocRaw["Hanamíku"] = "Hanamiku" -- travelsMap.xml: Hanamíku
TR_OfficialLocRaw["Harndirion"] = "Harndirion" -- travelsMap.xml: Harndirion
TR_OfficialLocRaw["Harwick"] = "Harwick" -- travelsMap.xml: Harwick
TR_OfficialLocRaw["Hebatokh"] = "Hêbatokh" -- travelsMap.xml: Hêbatokh
TR_OfficialLocRaw["Helethir"] = "Helethir" -- travelsMap.xml: Helethir
TR_OfficialLocRaw["Helm's Deep"] = "Gouffre de Helm" -- travelsMap.xml: Helm's Deep
TR_OfficialLocRaw["Hengstacer Farm"] = "Ferme d'Anstacier" -- travelsMap.xml: Hengstacer Farm
TR_OfficialLocRaw["Henneth Annun"] = "Henneth Annûn" -- travelsMap.xml: Henneth Annûn
TR_OfficialLocRaw["Herne"] = "Herne" -- travelsMap.xml: Herne
TR_OfficialLocRaw["High Crag"] = "Hautes Falaises" -- travelsMap.xml: High Crag
TR_OfficialLocRaw["High King's Crossing"] = "Le Carrefour du Haut-Roi" -- travelsMap.xml: High King's Crossing
TR_OfficialLocRaw["High Moor"] = "Haute Lande" -- geoAreas.xml: High Moor
TR_OfficialLocRaw["Hlithseld"] = "Hlithseld" -- travelsMap.xml: Hlithseld
TR_OfficialLocRaw["Hobbiton"] = "Hobbitebourg" -- travelsMap.xml: Hobbiton
TR_OfficialLocRaw["Hrimbarg"] = "Hrimbarg" -- travelsMap.xml: Hrimbarg
TR_OfficialLocRaw["Hudnul-meden"] = "Hudnul-meden" -- travelsWeb.xml: Hudnul-meden
TR_OfficialLocRaw["Hultvis"] = "Hultvis" -- travelsMap.xml: Hultvís
TR_OfficialLocRaw["Hulzidar"] = "Hulzidâr" -- travelsMap.xml: Hulzidâr
TR_OfficialLocRaw["Hunter's Camp"] = "Camp des chasseurs" -- travelsMap.xml: Hunter's Camp
TR_OfficialLocRaw["Hytbold"] = "Hytbold" -- travelsMap.xml: Hytbold
TR_OfficialLocRaw["Iaphel"] = "Iaphel" -- travelsMap.xml: Iaphel
TR_OfficialLocRaw["Ibdekh-buzru"] = "Ibdêkh-buzru (Tassau-terres centrales)" -- travelsMap.xml: Ibdêkh-buzru (Central Welkin-lofts)
TR_OfficialLocRaw["Ilzag Khul"] = "Ilzag Khûl" -- travelsMap.xml: Ilzag Khûl
TR_OfficialLocRaw["Imloth Melui"] = "Imloth Melui" -- travelsMap.xml: Imloth Melui
TR_OfficialLocRaw["Imrekh-guthlu"] = "Imrêkh-guthlu (Ouest de Matugarde)" -- travelsMap.xml: Imrêkh-guthlu (Western Máttugard)
TR_OfficialLocRaw["Ingar-Garash"] = "Ingar-garâsh" -- travelsMap.xml: Ingar-garâsh
TR_OfficialLocRaw["Ingaruma"] = "Ingarûma" -- travelsMap.xml: Ingarûma
TR_OfficialLocRaw["Inner Caras Galadhon"] = "Caras Galadhon intérieur" -- travelsMap.xml: Inner Caras Galadhon
TR_OfficialLocRaw["Iorelen's Camp"] = "Camp d'Iorelen" -- travelsMap.xml: Iorelen's Camp
TR_OfficialLocRaw["Iridir"] = "Iridir" -- travelsMap.xml: Iridír
TR_OfficialLocRaw["Isengard"] = "Isengard" -- travelsMap.xml: Isengard
TR_OfficialLocRaw["Itekh-ken"] = "Itekh-kên" -- travelsMap.xml: Itekh-kên
TR_OfficialLocRaw["Jadambor"] = "Jadambor" -- travelsMap.xml: Jadambor
TR_OfficialLocRaw["Jarnfast"] = "Jarnfast" -- travelsMap.xml: Járnfast
TR_OfficialLocRaw["Jax Phanal"] = "Jax Phanâl" -- travelsMap.xml: Jax Phanâl
TR_OfficialLocRaw["Jazargund"] = "Jazârgund" -- travelsMap.xml: Jazârgund
TR_OfficialLocRaw["Jiret-menesh"] = "Jiret-menêsh" -- travelsMap.xml: Jiret-menêsh
TR_OfficialLocRaw["Jirush"] = "Jirush" -- travelsMap.xml: Jirush
TR_OfficialLocRaw["Kafagur"] = "Kafagur" -- landmarks.xml: Kafagur
TR_OfficialLocRaw["Kauppa-kohta"] = "Kauppa-kohta" -- travelsMap.xml: Kauppa-kohta
TR_OfficialLocRaw["Ken Taghlim"] = "Kên Taghlim" -- travelsMap.xml: Kên Taghlim
TR_OfficialLocRaw["Khanag Gur"] = "Khanâg Gur" -- travelsMap.xml: Khanâg Gur
TR_OfficialLocRaw["Kheb Hanut"] = "Kheb Hanût" -- travelsMap.xml: Kheb Hanût
TR_OfficialLocRaw["Khomar Bóha"] = "Khomar Boha" -- travelsWeb.xml: Khomar Bóha
TR_OfficialLocRaw["Khur Azan"] = "Khur Azan" -- travelsWeb.xml: Khur Azan
TR_OfficialLocRaw["Khutra"] = "Khûtra" -- travelsMap.xml: Khûtra
TR_OfficialLocRaw["King's Crossing"] = "Carrefour du roi - Trajet en bateau" -- travelsWeb.xml: King's Crossing - Boat Travel
TR_OfficialLocRaw["Kings End"] = "Mort des rois" -- geoAreas.xml: Kings' End
TR_OfficialLocRaw["Kingstead Meadows Homesteads"] = "Résidences des prairies de Terre-du-Roi" -- travelsWeb.xml: Kingstead Meadows Homesteads
TR_OfficialLocRaw["Kruha-surja"] = "Kruha-sûrja" -- travelsMap.xml: Kruha-sûrja
TR_OfficialLocRaw["Kur Anzar"] = "Kûr Anzar" -- travelsMap.xml: Kûr Anzar
TR_OfficialLocRaw["Kuru-leiri"] = "Kuru-leiri" -- travelsMap.xml: Kuru-leiri
TR_OfficialLocRaw["Laivarth"] = "Laivarth" -- travelsMap.xml: Laivárth
TR_OfficialLocRaw["Lake-town"] = "Ville du Lac" -- travelsMap.xml: Lake-town
TR_OfficialLocRaw["Lalia's Market"] = "Marché de Lalia" -- dungeons.xml: Lalia's Market
TR_OfficialLocRaw["Lancrath"] = "Lancrath" -- travelsMap.xml: Lancrath
TR_OfficialLocRaw["Last Homely House"] = "Dernière Maison Simple" -- travelsMap.xml: The Last Homely House
TR_OfficialLocRaw["Leitstath"] = "Leitstath (Sud de Câr Bronach)" -- travelsMap.xml: Leitstáth (Southern Câr Bronach)
TR_OfficialLocRaw["Lhan Garan"] = "Lhan Garan" -- travelsMap.xml: Lhan Garan
TR_OfficialLocRaw["Lhan Rhos"] = "Lhan Rhos" -- travelsMap.xml: Lhan Rhos
TR_OfficialLocRaw["Lhan Tarren"] = "Lhan Tarren" -- travelsMap.xml: Lhan Tarren
TR_OfficialLocRaw["Lhanuch"] = "Lhanoch" -- travelsMap.xml: Lhanuch
TR_OfficialLocRaw["Limlight Gorge"] = "Gorge du Limeclair" -- travelsMap.xml: Limlight Gorge
TR_OfficialLocRaw["Limlok"] = "Limlók" -- travelsMap.xml: Limlók
TR_OfficialLocRaw["Linhir"] = "Linhir" -- travelsMap.xml: Linhir
TR_OfficialLocRaw["Lintrev"] = "Lintrev" -- travelsMap.xml: Lintrev
TR_OfficialLocRaw["Lond Cirion"] = "Lond Cirion" -- travelsMap.xml: Lond Cirion
TR_OfficialLocRaw["Long Cleeve"] = "Longueclève" -- travelsMap.xml: Long Cleeve
TR_OfficialLocRaw["Lothgobel"] = "Lothgobel (Gondor royal)" -- travelsMap.xml: Lothgobel (King's Gondor)
TR_OfficialLocRaw["Lothlorien"] = "Lothlórien" -- travelsMap.xml: Lothlórien
TR_OfficialLocRaw["Lyndelby"] = "Lyndelby" -- travelsMap.xml: Lyndelby
TR_OfficialLocRaw["Maergrind"] = "Maergrind (Est de Matugarde)" -- travelsMap.xml: Maergrind (Eastern Máttugard)
TR_OfficialLocRaw["Magh Ashtu"] = "Magh Ashtu" -- travelsMap.xml: Magh Ashtu
TR_OfficialLocRaw["Malbarth"] = "Malbarth" -- travelsMap.xml: Malbarth
TR_OfficialLocRaw["Malgama"] = "Malgâma" -- travelsMap.xml: Malgâma
TR_OfficialLocRaw["Mansig's Encampment"] = "Camp de Mansig" -- travelsMap.xml: Mansig's Encampment
TR_OfficialLocRaw["Mar Naphra"] = "Mâr Naphra" -- travelsMap.xml: Mâr Naphra
TR_OfficialLocRaw["Maur Tulhau"] = "Maur Tulhau" -- travelsMap.xml: Maur Tulhau
TR_OfficialLocRaw["Mekab-kuphar"] = "Mekab-kuphâr" -- travelsMap.xml: Mekab-kuphâr
TR_OfficialLocRaw["Mekhem-bizru"] = "Mekhem-bizru" -- travelsMap.xml: Mekhem-bizru
TR_OfficialLocRaw["Melgobas"] = "Melgobas" -- travelsMap.xml: Melgobas
TR_OfficialLocRaw["Meluinen"] = "Meluinen" -- travelsMap.xml: Meluinen
TR_OfficialLocRaw["Men Erain"] = "Men Erain - Voyage en bateau" -- travelsMap.xml: Men Erain - Boat Travel
TR_OfficialLocRaw["Mereham"] = "Franc-Bourg" -- travelsMap.xml: Mereham
TR_OfficialLocRaw["Michel Delving"] = "Grand'Cave" -- travelsMap.xml: Michel Delving
TR_OfficialLocRaw["Middlemead"] = "Bourgmitan" -- travelsMap.xml: Middlemead
TR_OfficialLocRaw["Minas Morgul"] = "Minas Morgul" -- travelsMap.xml: Minas Morgul
TR_OfficialLocRaw["Minas Tirith"] = "Minas Tirith" -- travelsMap.xml: Minas Tirith
TR_OfficialLocRaw["Mithechad"] = "Mithechad" -- travelsMap.xml: Mithechad
TR_OfficialLocRaw["Morlad"] = "Morlad" -- travelsMap.xml: Morlad
TR_OfficialLocRaw["Mossward"] = "Bois-de-Mousse" -- travelsMap.xml: Mossward
TR_OfficialLocRaw["Nagakhedi"] = "Nagakhêdi" -- travelsMap.xml: Nagakhêdi
TR_OfficialLocRaw["Nameless Places"] = "Des lieux sans nom" -- travelsWeb.xml: Nameless Places
TR_OfficialLocRaw["Nan Tornaeth"] = "Nan Tornaeth" -- geoAreas.xml: Nan Tornaeth
TR_OfficialLocRaw["Nashubu"] = "Nashûbu" -- travelsMap.xml: Nashûbu
TR_OfficialLocRaw["Needlehole"] = "Chas-de-l'Aiguille" -- travelsMap.xml: Needlehole
TR_OfficialLocRaw["Neruzig"] = "Nêruzig" -- travelsMap.xml: Nêruzig
TR_OfficialLocRaw["Nobottle"] = "Nobottle" -- travelsMap.xml: Nobottle
TR_OfficialLocRaw["Noglond"] = "Noglond" -- travelsMap.xml: Noglond
TR_OfficialLocRaw["North Trollshaws"] = "Trouée des Trolls Nord" -- geoAreas.xml: North Trollshaws
TR_OfficialLocRaw["North-gate"] = "Porte nord" -- travelsMap.xml: North-gate
TR_OfficialLocRaw["Northern Shore"] = "Étang aux Iris - Rive nord" -- travelsMap.xml: Gladdenmere - Northern Shore
TR_OfficialLocRaw["Oatbarton"] = "Castelorge" -- travelsMap.xml: Oatbarton
TR_OfficialLocRaw["Oserley"] = "Oserley" -- travelsMap.xml: Oserley
TR_OfficialLocRaw["Osgiliath"] = "Osgiliath" -- travelsMap.xml: Osgiliath
TR_OfficialLocRaw["Ost Anglebed"] = "Ost Anglebed" -- travelsMap.xml: Ost Anglebed
TR_OfficialLocRaw["Ost Arndir"] = "Ost Arndir" -- travelsMap.xml: Ost Arndir
TR_OfficialLocRaw["Ost Forod"] = "Ost Forod" -- travelsMap.xml: Ost Forod
TR_OfficialLocRaw["Ost Galadh"] = "Ost Galadh" -- travelsMap.xml: Ost Galadh
TR_OfficialLocRaw["Ost Guruth"] = "Ost Guruth" -- travelsMap.xml: Ost Guruth
TR_OfficialLocRaw["Ost Lontir"] = "Ost Lontir (Gondor Royal)" -- travelsMap.xml: Ost Lontir (King's Gondor)
TR_OfficialLocRaw["Ost Rimmon"] = "Ost Rimmon" -- travelsMap.xml: Ost Rimmon
TR_OfficialLocRaw["Othrikar"] = "Othrikar" -- travelsMap.xml: Othrikar
TR_OfficialLocRaw["Parth Celebrant"] = "Parth Célébrant" -- travelsMap.xml: Parth Celebrant
TR_OfficialLocRaw["Parth Galen"] = "Parth Galen" -- travelsMap.xml: Parth Galen
TR_OfficialLocRaw["Parth Rest"] = "Parth Repos (Gondor royal)" -- travelsMap.xml: Parth Rest (King's Gondor)
TR_OfficialLocRaw["Pelargir East Gate"] = "Porte est de Pelargir" -- travelsWeb.xml: Pelargir East Gate
TR_OfficialLocRaw["Pelargir West Gate"] = "Porte ouest de Pelargir" -- travelsWeb.xml: Pelargir West Gate
TR_OfficialLocRaw["Pelargir"] = "Pelargir (Gondor royal)" -- travelsWeb.xml: Pelargir (King's Gondor)
TR_OfficialLocRaw["Pynti-peldot"] = "Pynti-peldot" -- travelsMap.xml: Pynti-peldot
TR_OfficialLocRaw["Rakhatab"] = "Rakhatâb" -- travelsMap.xml: Rakhatâb
TR_OfficialLocRaw["Riders' Stand"] = "Défense des Cavaliers" -- geoAreas.xml: Riders' Stand
TR_OfficialLocRaw["Rivendell Stables"] = "Écuries de Fondcombe" -- travelsMap.xml: Rivendell Stables
TR_OfficialLocRaw["Rohirrim Scout-camp"] = "Camp d'éclaireurs rohirrim" -- travelsMap.xml: Rohirrim Scout-camp
TR_OfficialLocRaw["Ruin of Pel Duven"] = "Ruines de Pel Dúven" -- geoAreas.xml: Ruin of Pel Dúven
TR_OfficialLocRaw["Ruins of Dingarth"] = "Ruines de Díngarth" -- travelsMap.xml: Ruins of Díngarth
TR_OfficialLocRaw["Ruins of Dol Guldur"] = "Dol Guldur (rasée)" -- parchmentMaps.xml: Dol Guldur (razed)
TR_OfficialLocRaw["Rushgore"] = "Rushgore" -- travelsMap.xml: Rushgore
TR_OfficialLocRaw["Sar Marsag"] = "Sâr Marsag" -- travelsMap.xml: Sâr Marsag
TR_OfficialLocRaw["Sardol"] = "Sardol (Gondor Royal)" -- travelsMap.xml: Sardol (King's Gondor)
TR_OfficialLocRaw["Sarn Ford"] = "Gué de Sarn" -- travelsMap.xml: Sarn Ford
TR_OfficialLocRaw["Scurloc Farm"] = "Ferme des Scurloc" -- travelsMap.xml: Scurloc Farm
TR_OfficialLocRaw["Scylfig"] = "Scylfig" -- travelsMap.xml: Scylfig
TR_OfficialLocRaw["Second Hall Camp-site"] = "Campement de la Seconde salle" -- travelsWeb.xml: Second Hall Camp-site
TR_OfficialLocRaw["Sen Chatak"] = "Sen Chatâk" -- travelsMap.xml: Sen Chatâk
TR_OfficialLocRaw["Shadowed Refuge"] = "Refuge des Ombres" -- travelsMap.xml: Shadowed Refuge
TR_OfficialLocRaw["Shengarash"] = "Shengarâsh" -- travelsMap.xml: Shengarâsh
TR_OfficialLocRaw["Shire Homesteads"] = "Résidences de la Comté" -- travelsWeb.xml: Shire Homesteads
TR_OfficialLocRaw["Shonith"] = "Shonith" -- travelsMap.xml: Shonith
TR_OfficialLocRaw["Silvertine Work-site"] = "Chantier de la Corne d'argent" -- travelsWeb.xml: Silvertine Work-site
TR_OfficialLocRaw["Skald's Drop"] = "Falaise du skalde" -- travelsMap.xml: Skald's Drop
TR_OfficialLocRaw["Skarhald"] = "Skarhald" -- travelsMap.xml: Skarháld
TR_OfficialLocRaw["Snowbourn"] = "Neigebronne" -- travelsMap.xml: Snowbourn
TR_OfficialLocRaw["Sormedan"] = "Sormedân" -- travelsMap.xml: Sormedân
TR_OfficialLocRaw["South Bree"] = "Bree Sud" -- travelsMap.xml: South Bree
TR_OfficialLocRaw["Southern Shore"] = "Étang aux Iris - Rive sud" -- travelsMap.xml: Gladdenmere - Southern Shore
TR_OfficialLocRaw["Stangard"] = "Stangarde" -- travelsMap.xml: Stangard
TR_OfficialLocRaw["Steepset"] = "L'Escarpade (Gundabad) - Voyage rapide" -- travelsWeb.xml: Steepset (Gundabad) - Swift Travel
TR_OfficialLocRaw["Stock"] = "Stock" -- travelsMap.xml: Stock
TR_OfficialLocRaw["Stoke"] = "Stoke" -- travelsMap.xml: Stoke
TR_OfficialLocRaw["Sudulthurkh Outpost"] = "Avant-poste de Sudulthurkh" -- travelsWeb.xml: Sudulthurkh Outpost
TR_OfficialLocRaw["Sul Madash"] = "Sul Madash" -- travelsMap.xml: Sul Madásh
TR_OfficialLocRaw["Suri-kyla"] = "Sûri-kylä" -- travelsMap.xml: Sûri-kylä
TR_OfficialLocRaw["Swain's Guild-hall"] = "Siège de la guilde des maîtres d'équipage" -- travelsWeb.xml: Swain's Guild-hall
TR_OfficialLocRaw["Tadrent"] = "Tadrent" -- travelsMap.xml: Tadrent
TR_OfficialLocRaw["Taen Orwath"] = "Taen Orwath" -- travelsMap.xml: Taen Orwath
TR_OfficialLocRaw["Tal Methedras Gate"] = "Porte de Tâl Methedras" -- travelsMap.xml: Tâl Methedras Gate
TR_OfficialLocRaw["Tham Lumren"] = "Tham Lumren" -- travelsMap.xml: Tham Lumren
TR_OfficialLocRaw["Tham Periain"] = "Tham Periain" -- dungeons.xml: Tham Periain
TR_OfficialLocRaw["Tham Taerdol"] = "Tham Taerdol" -- travelsMap.xml: Tham Taerdol
TR_OfficialLocRaw["Thangulhad"] = "Thangulhad" -- travelsMap.xml: Thangúlhad
TR_OfficialLocRaw["Tharakh Bazan"] = "Tharâkh Bazân" -- travelsMap.xml: Tharâkh Bazân
TR_OfficialLocRaw["Tharbad"] = "Tharbad" -- travelsMap.xml: Tharbad
TR_OfficialLocRaw["The Carrock - Eagle"] = "Le Carrock" -- travelsWeb.xml: The Carrock
TR_OfficialLocRaw["The Dawn-warden"] = "Le Gardien de l'aube" -- travelsMap.xml: The Dawn-warden
TR_OfficialLocRaw["The Deep Descent"] = "La Longue Descente" -- landmarks.xml: The Deep Descent
TR_OfficialLocRaw["The Dulkar"] = "Le Dûlkar" -- travelsMap.xml: The Dûlkar
TR_OfficialLocRaw["The Eavespires"] = "Hautecime - Voyage en bateau" -- travelsMap.xml: The Eavespires - Boat Travel
TR_OfficialLocRaw["The Eyrie - Eagle"] = "L'aire des aigles" -- travelsWeb.xml: The Eyrie
TR_OfficialLocRaw["The Fanged Pit"] = "Fosse Mordante" -- travelsMap.xml: The Fanged Pit
TR_OfficialLocRaw["The Forsaken Inn"] = "L'Auberge Abandonnée" -- travelsMap.xml: The Forsaken Inn
TR_OfficialLocRaw["The Harlond"] = "Le Harlond" -- travelsMap.xml: The Harlond
TR_OfficialLocRaw["The Haunted Inn"] = "L'Auberge hantée" -- travelsMap.xml: The Haunted Inn
TR_OfficialLocRaw["The Last Bridge"] = "Le Dernier Pont" -- travelsMap.xml: The Last Bridge
TR_OfficialLocRaw["The Orc-watch"] = "Guet de l'Orque" -- travelsMap.xml: The Orc-watch
TR_OfficialLocRaw["The Party Tree"] = "L'Arbre de la Fête - Voyage rapide" -- travelsWeb.xml: The Party Tree - Swift Travel
TR_OfficialLocRaw["The Rotting Cellar"] = "Cellier Putride" -- travelsMap.xml: The Rotting Cellar
TR_OfficialLocRaw["The Slag-hills"] = "Collines arides" -- travelsMap.xml: The Slag-hills
TR_OfficialLocRaw["The Vile Maw"] = "La Gueule Ignoble" -- travelsMap.xml: The Vile Maw
TR_OfficialLocRaw["The Vinyards of Lorien"] = "Les Vignes de la Lórien" -- travelsMap.xml: The Vineyards of Lórien
TR_OfficialLocRaw["The War of Three Peaks"] = "La guerre des Trois Sommets - Voyage rapide" -- travelsWeb.xml: The War of Three Peaks - Swift Travel
TR_OfficialLocRaw["the War-stead"] = "Camp militaire des Rohirrim" -- travelsMap.xml: War-stead of the Rohirrim
TR_OfficialLocRaw["Thinglad"] = "Clairfine" -- travelsMap.xml: Thinglad
TR_OfficialLocRaw["Thokvist"] = "Thokvist" -- travelsMap.xml: Thokvist
TR_OfficialLocRaw["Thorenhad"] = "Thorenhad" -- travelsMap.xml: Thorenhad
TR_OfficialLocRaw["Thorin's Gate"] = "Porte de Thorin" -- travelsMap.xml: Thorin's Gate
TR_OfficialLocRaw["Thorin's Hall Homesteads"] = "Résidences du Palais de Thorin" -- travelsWeb.xml: Thorin's Hall Homesteads
TR_OfficialLocRaw["Thornhope"] = "Espéronce" -- travelsMap.xml: Thornhope
TR_OfficialLocRaw["Thrasi's Lodge"] = "Pavillon de chasse de Thrasi" -- travelsMap.xml: Thrasi's Lodge
TR_OfficialLocRaw["Threshold of the City"] = "Portes de la cité" -- geoAreas.xml: Threshold of the City
TR_OfficialLocRaw["Tighfield"] = "Champtoron" -- travelsMap.xml: Tighfield
TR_OfficialLocRaw["Tilmakhím"] = "Tilmakhim" -- travelsMap.xml: Tilmakhím
TR_OfficialLocRaw["Tinnudir"] = "Tinnudir" -- travelsMap.xml: Tinnudir
TR_OfficialLocRaw["To Kings End"] = "Mort des rois" -- geoAreas.xml: Kings' End
TR_OfficialLocRaw["To Minas Tirith, After the Battle"] = "Minas Tirith (après la bataille)" -- geoAreas.xml: Minas Tirith (After-battle)
TR_OfficialLocRaw["To Minas Tirith, Before the Battle"] = "Minas Tirith" -- travelsMap.xml: Minas Tirith
TR_OfficialLocRaw["To Riders' Stand"] = "Défense des Cavaliers" -- geoAreas.xml: Riders' Stand
TR_OfficialLocRaw["To the Cape of Belfalas"] = "Le Cap du Belfalas" -- geoAreas.xml: The Cape of Belfalas
TR_OfficialLocRaw["To the Field of Onslaught"] = "Champ du carnage" -- geoAreas.xml: Field of Onslaught
TR_OfficialLocRaw["To the Ruin of Pel Duven"] = "Ruines de Pel Dúven" -- geoAreas.xml: Ruin of Pel Dúven
TR_OfficialLocRaw["To the Threshold of the City"] = "Portes de la cité" -- geoAreas.xml: Threshold of the City
TR_OfficialLocRaw["Tornhad"] = "Tornhad" -- travelsMap.xml: Tornhad
TR_OfficialLocRaw["Trader's Wharf"] = "Quai des négociants - Trajet en bateau" -- travelsWeb.xml: Trader's Wharf - Boat Travel
TR_OfficialLocRaw["Travel to Dol Amroth"] = "Dol Amroth" -- travelsMap.xml: Dol Amroth
TR_OfficialLocRaw["Trestlebridge"] = "Pont-à-Tréteaux" -- travelsMap.xml: Trestlebridge
TR_OfficialLocRaw["Tumladen"] = "Tum Laden" -- travelsMap.xml: Tum Laden
TR_OfficialLocRaw["Twenty-first Hall"] = "Vingt et unième salle" -- travelsMap.xml: Twenty-first Hall
TR_OfficialLocRaw["Tyl Ruinen"] = "Tyl Ruinen - Voyage en bateau" -- travelsMap.xml: Tyl Ruinen - Boat Travel
TR_OfficialLocRaw["Tyrn Lhuig"] = "Tyrn Lhuig" -- landmarks.xml: Tyrn Lhuig
TR_OfficialLocRaw["Ub Nishir"] = "Ub Nishir" -- travelsMap.xml: Ub Nishir
TR_OfficialLocRaw["Udun Foothold"] = "Fort d'Udûn" -- travelsMap.xml: Udûn Foothold
TR_OfficialLocRaw["Umbar Baharbel"] = "Umbar Baharbêl" -- travelsWeb.xml: Umbar Baharbêl
TR_OfficialLocRaw["Underharrow"] = "Sousharrow" -- travelsMap.xml: Underharrow
TR_OfficialLocRaw["Urmakh"] = "Urmâkh" -- travelsMap.xml: Urmâkh
TR_OfficialLocRaw["Vartulin"] = "Vartulin" -- travelsMap.xml: Vartúlin
TR_OfficialLocRaw["Vegbar"] = "Vegbar" -- travelsMap.xml: Vegbár
TR_OfficialLocRaw["Vindurhal"] = "Vindurhal" -- travelsMap.xml: Vindurhal
TR_OfficialLocRaw["Voyage's End"] = "La fin du voyage" -- travelsMap.xml: Voyage's End
TR_OfficialLocRaw["Walstow"] = "Rangeval" -- travelsMap.xml: Walstow
TR_OfficialLocRaw["Watchers' Roost"] = "Repaire des Veilleurs (Sombrelac)" -- travelsMap.xml: Watchers' Roost (Gloomingtarn)
TR_OfficialLocRaw["West Bree"] = "Bree Ouest" -- travelsMap.xml: West Bree
TR_OfficialLocRaw["West Pelargir"] = "Pelargir ouest" -- travelsMap.xml: West Pelargir
TR_OfficialLocRaw["Western Eregion"] = "Eregion occidentale" -- travelsMap.xml: Western Eregion
TR_OfficialLocRaw["Woodhurst"] = "Tertrebois" -- travelsMap.xml: Woodhurst
TR_OfficialLocRaw["Wrackwade Crossing"] = "La Traversée du Gué Dévasté" -- travelsMap.xml: Wrackwade Crossing
TR_OfficialLocRaw["Wulf's Cleft Overlook"] = "Promontoire de la Faille de Wulf" -- travelsMap.xml: Wulf's Cleft Overlook
TR_OfficialLocRaw["Zaduru"] = "Zadûru" -- travelsMap.xml: Zadûru
TR_OfficialLocRaw["Zajana"] = "Zajâna" -- travelsMap.xml: Zajâna
TR_OfficialLocRaw["Zarsatrad"] = "Zarsatrâd" -- travelsMap.xml: Zarsatrâd
TR_OfficialLocRaw["Zidir-nesad"] = "Zidir-nesad, l'Escarpade (nord de Matugarde)" -- travelsMap.xml: Zidir-nesad, the Steepset (Northern Máttugard)
TR_OfficialLocRaw["Zigilgund"] = "Zigilgund" -- travelsMap.xml: Zigilgund
TR_OfficialLocRaw["Zirakazhar"] = "Zirakazhâr" -- travelsWeb.xml: Zirakazhâr
TR_OfficialLocRaw["Zirakzigil"] = "Zirakzigil" -- travelsMap.xml: Zirakzigil
TR_OfficialLocRaw["Zudramdan"] = "Zudramdân" -- travelsMap.xml: Zudramdân

TR_OfficialZoneRaw["Angmar"] = "Angmar" -- travelsMap.xml: Angmar
TR_OfficialZoneRaw["Bree-Land"] = "Pays de Bree" -- travelsMap.xml: Bree-land
TR_OfficialZoneRaw["Cape of Umbar"] = "Cap d'Umbar" -- parchmentMaps.xml: Cape of Umbar
TR_OfficialZoneRaw["Cardolan"] = "Cardolan" -- travelsMap.xml: Cardolan
TR_OfficialZoneRaw["Central Gondor"] = "Centre du Gondor" -- travelsMap.xml: Central Gondor
TR_OfficialZoneRaw["Dunland"] = "Pays de Dun" -- travelsMap.xml: Dunland
TR_OfficialZoneRaw["Dwarf-holds"] = "Les bastions des Nains" -- geoAreas.xml: The Dwarf-holds
TR_OfficialZoneRaw["East Gondor"] = "Est du Gondor" -- travelsMap.xml: Eastern Gondor
TR_OfficialZoneRaw["East Rohan"] = "Rohan Est" -- travelsMap.xml: East Rohan
TR_OfficialZoneRaw["Elderslade"] = "Val-d'Aïeul" -- travelsMap.xml: Elderslade
TR_OfficialZoneRaw["Enedwaith"] = "Enedwaith" -- travelsMap.xml: Enedwaith
TR_OfficialZoneRaw["Ered Luin"] = "Ered Luin" -- travelsMap.xml: Ered Luin
TR_OfficialZoneRaw["Eregion"] = "Eregion" -- travelsMap.xml: Eregion
TR_OfficialZoneRaw["Ettenmoors"] = "Landes d'Etten" -- travelsWeb.xml: Ettenmoors
TR_OfficialZoneRaw["Evendim"] = "Evendim" -- travelsMap.xml: Evendim
TR_OfficialZoneRaw["Far Anorien"] = "Lointain Anórien" -- travelsMap.xml: Far Anórien
TR_OfficialZoneRaw["Forochel"] = "Forochel" -- travelsMap.xml: Forochel
TR_OfficialZoneRaw["Gorgoroth"] = "Gorgoroth" -- geoAreas.xml: Gorgoroth
TR_OfficialZoneRaw["Great River"] = "Le Grand Fleuve" -- travelsMap.xml: The Great River
TR_OfficialZoneRaw["Gundabad"] = "Gundabad" -- travelsMap.xml: Gundabad
TR_OfficialZoneRaw["King's Gondor"] = "Gondor royal" -- travelsMap.xml: King's Gondor
TR_OfficialZoneRaw["Lone-lands"] = "Terres Solitaires" -- travelsMap.xml: Lone-Lands
TR_OfficialZoneRaw["Lothlorien"] = "Lothlórien" -- travelsMap.xml: Lothlórien
TR_OfficialZoneRaw["March of the King"] = "Marche du Roi" -- parchmentMaps.xml: March of the King
TR_OfficialZoneRaw["Mirkwood"] = "Forêt Noire" -- travelsMap.xml: Mirkwood
TR_OfficialZoneRaw["Misty Mountains"] = "Monts Brumeux" -- travelsMap.xml: Misty Mountains
TR_OfficialZoneRaw["Mordor Besieged"] = "Le siège du Mordor" -- geoAreas.xml: Mordor Besieged
TR_OfficialZoneRaw["Morgul Vale"] = "Vallée de Morgul" -- travelsMap.xml: Morgul Vale
TR_OfficialZoneRaw["Moria"] = "Moria" -- travelsMap.xml: Moria
TR_OfficialZoneRaw["Mur Ghala"] = "Mûr Ghala (la Crête de l'Abondance)" -- parchmentMaps.xml: Mûr Ghala (The Ridge of Plenty)
TR_OfficialZoneRaw["North Downs"] = "Hauts du Nord" -- travelsMap.xml: North Downs
TR_OfficialZoneRaw["Old Anorien"] = "Ancien Anórien" -- travelsMap.xml: Old Anórien
TR_OfficialZoneRaw["Outer Gondor"] = "Gondor extérieur" -- parchmentMaps.xml: Outer Gondor
TR_OfficialZoneRaw["Swanfleet"] = "Les Noues des cygnes" -- travelsMap.xml: Swanfleet
TR_OfficialZoneRaw["The Shire"] = "Comté" -- travelsMap.xml: The Shire
TR_OfficialZoneRaw["The Wastes"] = "Les Landes désertiques[fp]" -- travelsMap.xml: The Wastes
TR_OfficialZoneRaw["Trollshaws"] = "Trouée des Trolls" -- travelsMap.xml: Trollshaws
TR_OfficialZoneRaw["Vales of Anduin"] = "Val d'Anduin" -- travelsMap.xml: Vales of Anduin
TR_OfficialZoneRaw["Valley of Ikorbad"] = "Vallée d'Ikorbân" -- travelsMap.xml: Valley of Ikorbân
TR_OfficialZoneRaw["Wells of Langflood"] = "Puits du Long Fleuve" -- travelsMap.xml: Wells of Langflood
TR_OfficialZoneRaw["West Gondor"] = "Ouest du Gondor" -- travelsMap.xml: Western Gondor
TR_OfficialZoneRaw["West Rohan"] = "Ouest du Rohan" -- travelsMap.xml: Western Rohan
TR_OfficialZoneRaw["Wildermore"] = "Landes farouches" -- travelsMap.xml: Wildermore
TR_OfficialZoneRaw["Yondershire"] = "Comté lointain" -- travelsMap.xml: Yondershire

TR_OfficialAreaRaw["Adagim"] = "Adagim, la Forêt morte" -- geoAreas.xml: Adagím, the Moulder-wood
TR_OfficialAreaRaw["Ambarul"] = "Ambarûl" -- geoAreas.xml: Ambarûl
TR_OfficialAreaRaw["An Sheru"] = "An Shêru, l'Apogée du ciel" -- geoAreas.xml: An Shêru, the Height of the Sky
TR_OfficialAreaRaw["Anfalas"] = "Anfalas" -- geoAreas.xml: Anfalas
TR_OfficialAreaRaw["Angle of Mitheithel"] = "L'Angle de Mitheithel" -- geoAreas.xml: The Angle of Mitheithel
TR_OfficialAreaRaw["Annuminas"] = "Annuminas" -- travelsMap.xml: Annúminas
TR_OfficialAreaRaw["Beacon Hills"] = "Collines des balises" -- geoAreas.xml: Beacon Hills
TR_OfficialAreaRaw["Blackroot Vale"] = "Vallée de la Racine Noire" -- geoAreas.xml: Blackroot Vale
TR_OfficialAreaRaw["Bree"] = "Bree" -- geoAreas.xml: Bree
TR_OfficialAreaRaw["Broadacres"] = "Grands-arpents" -- geoAreas.xml: Broadacres
TR_OfficialAreaRaw["Cape of Belfalas"] = "Le Cap du Belfalas" -- geoAreas.xml: The Cape of Belfalas
TR_OfficialAreaRaw["Car Bronach"] = "Câr Bronach" -- geoAreas.xml: Câr Bronach
TR_OfficialAreaRaw["Caras Galadhon"] = "Caras Galadhon" -- travelsMap.xml: Caras Galadhon
TR_OfficialAreaRaw["Clovengap"] = "Fond-de-fosse" -- geoAreas.xml: Clovengap
TR_OfficialAreaRaw["Deepscrave"] = "Tordesoif" -- geoAreas.xml: Deepscrave
TR_OfficialAreaRaw["Dol Guldur"] = "Dol Guldur" -- geoAreas.xml: Dol Guldur
TR_OfficialAreaRaw["Dor-en-ernil"] = "Dor-en-Ernil" -- geoAreas.xml: Dor-en-Ernil
TR_OfficialAreaRaw["Durin's Way"] = "Voie de Durin" -- geoAreas.xml: Durin's Way
TR_OfficialAreaRaw["Eastfold"] = "Estfolde" -- geoAreas.xml: Eastfold
TR_OfficialAreaRaw["Entwash Vale"] = "La vallée de l'Entalluve" -- geoAreas.xml: The Entwash Vale
TR_OfficialAreaRaw["Entwood"] = "Forêt d'Ent" -- geoAreas.xml: Entwood
TR_OfficialAreaRaw["Ephel Angren"] = "Ephel Angren" -- geoAreas.xml: Ephel Angren
TR_OfficialAreaRaw["Erebor"] = "Erebor" -- travelsMap.xml: Erebor
TR_OfficialAreaRaw["Ered Mithrin"] = "Ered Mithrin" -- travelsMap.xml: Ered Mithrin
TR_OfficialAreaRaw["Eryn Lasgalen"] = "Eryn Lasgalen" -- geoAreas.xml: Eryn Lasgalen
TR_OfficialAreaRaw["Foundations of Stone"] = "Fondations de Pierre" -- geoAreas.xml: The Foundations of Stone
TR_OfficialAreaRaw["Galtrev"] = "Galtrev" -- travelsMap.xml: Galtrev
TR_OfficialAreaRaw["Gap of Rohan"] = "Trouée du Rohan" -- geoAreas.xml: Gap of Rohan
TR_OfficialAreaRaw["Gloomingtarn"] = "Sombrelac" -- geoAreas.xml: Gloomingtarn
TR_OfficialAreaRaw["Hatokali Fells"] = "Monts de l'Hatokali" -- geoAreas.xml: The Hatokáli Fells
TR_OfficialAreaRaw["Havens of Belfalas"] = "Les Havres de Belfalas" -- geoAreas.xml: The Havens of Belfalas
TR_OfficialAreaRaw["Helm's Deep"] = "Gouffre de Helm" -- travelsMap.xml: Helm's Deep
TR_OfficialAreaRaw["Idagal"] = "Idagâl, la Trombe-sèche" -- geoAreas.xml: Idagâl, the Dry-whelm
TR_OfficialAreaRaw["Imhular"] = "Imhûlar" -- geoAreas.xml: Imhûlar
TR_OfficialAreaRaw["Iron Hills"] = "Monts du Fer" -- travelsMap.xml: Iron Hills
TR_OfficialAreaRaw["Khud Zagin"] = "Khûd Zagin" -- geoAreas.xml: Khûd Zagin
TR_OfficialAreaRaw["Kighan"] = "Kighân, le Valtondu" -- geoAreas.xml: Kighân, the Shornvale
TR_OfficialAreaRaw["Kingstead"] = "Terre-du-Roi" -- geoAreas.xml: Kingstead
TR_OfficialAreaRaw["Lamedon"] = "Lamedon" -- geoAreas.xml: Lamedon
TR_OfficialAreaRaw["Lebennin"] = "Lebennin" -- geoAreas.xml: Lebennin
TR_OfficialAreaRaw["Lossarnach"] = "Lossarnach" -- geoAreas.xml: Lossarnach
TR_OfficialAreaRaw["Lower Lebennin"] = "Bas-Lebennin" -- geoAreas.xml: Lower Lebennin
TR_OfficialAreaRaw["Mattugard"] = "Matugarde" -- geoAreas.xml: Máttugard
TR_OfficialAreaRaw["Nan Curunir"] = "Nan Curunír" -- geoAreas.xml: Nan Curunír
TR_OfficialAreaRaw["Norcrofts"] = "Norcrofts" -- geoAreas.xml: Norcrofts
TR_OfficialAreaRaw["North Ithilien"] = "Ithilien du Nord" -- travelsMap.xml: North Ithilien
TR_OfficialAreaRaw["Nud-Melek"] = "Nud-melek" -- geoAreas.xml: Nud-melek
TR_OfficialAreaRaw["Osgiliath"] = "Osgiliath" -- travelsMap.xml: Osgiliath
TR_OfficialAreaRaw["Pelargir"] = "Pelargir (Gondor royal)" -- travelsWeb.xml: Pelargir (King's Gondor)
TR_OfficialAreaRaw["Pelennor"] = "Pelennor" -- geoAreas.xml: Pelennor
TR_OfficialAreaRaw["Pelennor Fields"] = "Les Champs du Pelennor (après la bataille)" -- geoAreas.xml: The Pelennor Fields (After-battle)
TR_OfficialAreaRaw["Pinnath Gelin"] = "Pinnath Gelin" -- geoAreas.xml: Pinnath Gelin
TR_OfficialAreaRaw["Pit of Stonejaws"] = "Fosse de Mâcherocs" -- geoAreas.xml: Pit of Stonejaws
TR_OfficialAreaRaw["Redhorn Lodes"] = "Filons du Rubicorne" -- geoAreas.xml: Redhorn Lodes
TR_OfficialAreaRaw["Ringlo Vale"] = "Val de Ringlo" -- geoAreas.xml: Ringló Vale
TR_OfficialAreaRaw["Rivendell"] = "Fondcombe" -- travelsWeb.xml: Rivendell
TR_OfficialAreaRaw["South Ithilien"] = "Ithilien du Sud" -- geoAreas.xml: South Ithilien
TR_OfficialAreaRaw["Stonedeans"] = "Pierreval" -- geoAreas.xml: Stonedeans
TR_OfficialAreaRaw["Sutcrofts"] = "Sutcrofts" -- geoAreas.xml: Sutcrofts
TR_OfficialAreaRaw["Taur Druadan"] = "Taur Drúadan" -- geoAreas.xml: Taur Drúadan
TR_OfficialAreaRaw["The Dale-lands"] = "Terres de Dale" -- geoAreas.xml: The Dale-lands
TR_OfficialAreaRaw["the East Wall"] = "Le Mur de l'Est" -- geoAreas.xml: The East Wall
TR_OfficialAreaRaw["The Flaming Deeps"] = "Profondeurs Ardentes" -- geoAreas.xml: The Flaming Deeps
TR_OfficialAreaRaw["the Great Delving"] = "Grande Prospection" -- geoAreas.xml: The Great Delving
TR_OfficialAreaRaw["the Silvertine Lodes"] = "Filons de la Corne d'Argent" -- geoAreas.xml: Silvertine Lodes
TR_OfficialAreaRaw["The War of Three Peaks"] = "La guerre des Trois Sommets - Voyage rapide" -- travelsWeb.xml: The War of Three Peaks - Swift Travel
TR_OfficialAreaRaw["the Water-works"] = "Système hydraulique" -- geoAreas.xml: The Water-works
TR_OfficialAreaRaw["the Wold"] = "Le Plateau" -- geoAreas.xml: The Wold
TR_OfficialAreaRaw["Thorin's Gate"] = "Porte de Thorin" -- travelsMap.xml: Thorin's Gate
TR_OfficialAreaRaw["Umbar Baharbel"] = "Umbar Baharbêl" -- travelsWeb.xml: Umbar Baharbêl
TR_OfficialAreaRaw["Upper Lebennin"] = "Haut-Lebennin" -- geoAreas.xml: Upper Lebennin
TR_OfficialAreaRaw["Urash Dar"] = "Urash Dâr" -- geoAreas.xml: Urash Dâr
TR_OfficialAreaRaw["Welkin-Lofts"] = "Tassau-terres" -- geoAreas.xml: Welkin-lofts
TR_OfficialAreaRaw["Westfold"] = "Westfold" -- geoAreas.xml: Westfold
TR_OfficialAreaRaw["Zelem-melek"] = "Zelem-melek" -- geoAreas.xml: Zelem-melek
